name: fingerprint_attendance
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  collection: ^1.19.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_libserialport: ^0.6.0
  hive_ce_flutter: ^2.3.3
  intl: ^0.19.0
  libserialport: ^0.3.0+1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.10.0
  solid_lints: ^0.3.2

flutter:
  uses-material-design: true
